# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KbDprsMj73IQIbD6MMyQKGlnInlmakwK
"""

print("hi")